config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'movies#index'
    get 'main', to: 'main#index', as: :main
    resources :categories, except: [:show]
    resources :movies
    get 'users', to: 'users#index', as: :users
  end

  match 'movies/:id/rate/:rating', to: 'ratings#index', via: [:get, :post], as: :rating
  get 'category/:category', to: 'movies#category', as: :category
  root to: "movies#index"

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', registration: 'register' }

  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < Admin::BaseController
  before_action :set_movie, only: %i[ show edit update destroy ]

  def index
    @movies = Movie.order(title: :asc)
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to admin_movie_path(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to admin_movie_path(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to admin_movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_movie
    @movie = Movie.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def movie_params
    params.require(:movie).permit(:title, :description, category_ids:[])
  end

  def set_active_main_menu_item
    @main_menu[:movies][:active] = true
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  # GET /movies or /movies.json
  def index
    @page = (params[:page] || 1).to_i
    @number_of_pages = (Movie.all.size / MOVIES_PER_PAGE.to_f).ceil
    
    if @page > @number_of_pages || @page < 1
      redirect_to movies_path, alert: "Wrong page number!" 
    else
      @movies = Movie.paginate(page: params[:page], per_page: MOVIES_PER_PAGE)
    end
  end

  def category
    @page = (params[:page] || 1).to_i
    @cat = params[:category].capitalize
    category_movies = Movie.joins(:category).where("categories.title = ?", @cat)
    @number_of_pages = (category_movies.size / MOVIES_PER_PAGE.to_f).ceil

    if @page > @number_of_pages || @page < 1
      redirect_to movies_path, alert: "Wrong page number!"
    else
      @movies = category_movies.paginate(page: params[:page], per_page: MOVIES_PER_PAGE)
      render "index"
    end
  end

  # GET /movies/1 or /movies/1.json
  def show
    @movie = Movie.find(params[:id])
    @current_users_rating ||= @movie.ratings.where(user: current_user).pick(:rating)
    
    if @movie.ratings.any?
      @average_rating = @movie.ratings.average(:rating).round(2) 
      @ratings_count = @movie.ratings.count(:rating)
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :description, :rating, category_ids:[])
    end
end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_expressrate.html.erb
<% @movies.each do |movie| %>
  <tr>
    <td><%= link_to movie.title, movie %></td>
    
    <% if current_user %>
      <td>
        <% if current_user.ratings.where(movie: movie).present? %>
          <p>
            Your rate:
            <strong>
              <%= movie.ratings.where(user: current_user).pluck(:rating)[0] %>
            </strong>
          </p>
        <% end %>
        
        <% (1..10).each do |n| %>
          <%= 
            link_to_if params[:page].nil? && params[:category].nil?, n, rating_path(id: movie, rating: n), method: :post, remote: true do
              link_to_if params[:page].nil? && !params[:category].nil?, n, rating_path(id: movie, rating: n, category: params[:category]), method: :post, remote: true do
                link_to_if !params[:page].nil? && params[:category].nil?, n, rating_path(id: movie, rating: n, page: params[:page]), method: :post, remote: true do
                  link_to n, rating_path(id: movie, rating: n, category: params[:category], page: params[:page]), method: :post, remote: true 
                end
              end
            end
          %>
        <% end %>
      </td>
    <% end %>
    
    <td><%= movie.description %></td>
    <td>
      <% movie.category.each do |c| %>
        <%= link_to c.title, category_path(category: c.title.downcase) %>
      <% end %>
    </td>
    <% if user_signed_in? && current_user.admin? %>
      <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
      <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </tr>
<% end %>

app/views/movies/_rate.html.erb
<div class="p-sm-3 p-md-5 mb-4 bg-light rounded-3 border">
  <div class="p-2 mt-2 mb-4 visible-xs">
    <div class="container-fluid py-1">

      <div class="row">
        <div class="col-xs-12 col-md-6">
          <h3 class="display-7 mb-1"><%= link_to movie.title, movie, style: "text-decoration: none; color: black" %></h3>
        </div>
        <div class="col-xs-12 col-md-6 text-md-end text-xs-start">
          <div class="d-inline-flex mb-2">
            <% if current_user %>
              <% if current_user.ratings.where(movie: movie).present? %>
                <% current_rating = movie.ratings.where(user: current_user).pick(:rating) %>
                
                <% (1..10).each do |n| %>
                  <% if n <= current_rating %>
                    <%= link_to(image_tag("/star-fill.svg", width: "20", class: "m-0"), rating_path(id: movie, rating: n, category: params[:category], page: params[:page]), method: :post, remote: true) %>                
                  <% else %>
                    <%= link_to(image_tag("/star.svg", width: "20", class: "m-0"), rating_path(id: movie, rating: n, category: params[:category], page: params[:page]), method: :post, remote: true) %>   
                  <% end %>
                <% end %>

              <% else %>
                <% (1..10).each do |n| %>
                  <%= link_to(image_tag("/star.svg", width: "20", class: "m-0"), rating_path(id: movie, rating: n, category: params[:category], page: params[:page]), method: :post, remote: true) %>
                <% end %>
              <% end %>
              
            <% end %>
          </div>
          
        </div>
      </div>
      
      <p class="fs-5"><%= movie.description %></p>
      
      <% movie.category.each do |c| %>
        <%= link_to c.title, category_path(category: c.title.downcase) %>
      <% end %>
      
    </div>
  </div>
</div>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<div class="m-3 px-2">
  <% if params[:category] %>
    <h2><%= params[:category].capitalize %></h2>
  <% else %>
    <h2>Movies</h2>
  <% end %>
</div>



<div id="rate">
  <%= render partial: 'rate', collection: @movies, as: :movie %>
</div>

<br>

<nav aria-label="Page navigation example">
  <ul class="pagination">
  <% if @page %>
    <% if @cat %>
      <li class="page-item"><%= link_to "First page", category_path, class: "page-link" if @page != 1 %></li>
      <li class="page-item"><%= link_to "Previous page", category_path(page: @page - 1), class: "page-link" if @page > 1 %></li>
      <li class="page-item"><%= link_to "Next page", category_path(page: @page + 1), class: "page-link" if @page < @number_of_pages %></li>
      <li class="page-item"><%= link_to "Last page", category_path(page: @number_of_pages), class: "page-link" if @page != @number_of_pages %></li>

    <% else %>
      <li class="page-item"><%= link_to "First page", movies_path, class: "page-link" if @page != 1 %></li>
      <li class="page-item"><%= link_to "Previous page", movies_path(page: @page - 1), class: "page-link" if @page > 1 %></li>
      <li class="page-item"><%= link_to "Next page", movies_path(page: @page + 1), class: "page-link" if @page < @number_of_pages %></li>
      <li class="page-item"><%= link_to "Last page", movies_path(page: @number_of_pages), class: "page-link" if @page != @number_of_pages %></li>
    <% end %>
  <% end %>
  </ul>
</nav>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/rate.js.erb
$('#rate').html("<%= j (render partial: 'movies/rate', collection: @movies, as: :movie) %>")

app/views/movies/show.html.erb
<div class="p-sm-3 p-md-5 mb-4 bg-light rounded-3 border mt-3">
  <div class="p-2 mt-2 mb-4 visible-xs">
    <div class="container-fluid py-1">

      <div class="row">
        <div class="col-xs-12 col-md-6">
          <h3 class="display-7 mb-1"><%= @movie.title %></h3>
        </div>
        <div class="col-xs-12 col-md-6 text-md-end text-xs-start">
          <div class="d-inline-flex mb-2">
            <% if user_signed_in? %>
              <% if @current_users_rating %>
                
                <% (1..10).each do |n| %>
                  <% if n <= @current_users_rating %>
                    <%= link_to(image_tag("/star-fill.svg", width: "20", class: "m-0"), rating_path(id: @movie, rating: n, category: params[:category], page: params[:page]), method: :post) %>
                  <% else %>
                    <%= link_to(image_tag("/star.svg", width: "20", class: "m-0"), rating_path(id: @movie, rating: n, category: params[:category], page: params[:page]), method: :post) %>
                  <% end %>
                <% end %>

              <% else %>
                <% (1..10).each do |n| %>
                  <%= link_to(image_tag("/star.svg", width: "20", class: "m-0"), rating_path(id: @movie, rating: n, category: params[:category], page: params[:page]), method: :post) %>
                <% end %>
              <% end %>
              
            <% end %>
          </div>
        </div>
      </div>
      
      <p class="fs-5">
        <%= @movie.description %>
      </p>
      <div class="my-3">
        <strong>Average rating:</strong>
        <%= @average_rating %> (number of ratings: <%= @ratings_count %>)
      </div>
      
      <% @movie.category.each do |c| %>
        <%= link_to c.title, category_path(category: c.title.downcase) %>
      <% end %>
      
    </div>
  </div>
</div>

<%= link_to 'Back', movies_path, class: "btn btn-secondary" %>