config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'movies#index'
    get 'main', to: 'main#index', as: :main
    resources :categories, except: [:show]
    resources :movies
    get 'users', to: 'users#index', as: :users
  end

  match 'movies/:id/rate/:rating', to: 'ratings#index', via: [:get, :post], as: :rating
  get 'category/:category', to: 'movies#category', as: :category
  root to: "movies#index"

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', registration: 'register' }

  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :categorisation, dependent: :destroy
  has_many :category, through: :categorisation
  has_many :ratings, dependent: :destroy
  has_many :users, through: :rating

  validates :title, presence: true
  validates :category, presence: true

  default_scope { order(title: :asc) }

  scope :paginate, -> (page:, per_page:) {
    page = (page || 1).to_i

    limit(per_page).offset((page - 1) * per_page)
  }
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < Admin::BaseController
  before_action :set_movie, only: %i[ show edit update destroy ]

  def index
    @movies = Movie.order(title: :asc)
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to admin_movie_path(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to admin_movie_path(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to admin_movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_movie
    @movie = Movie.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def movie_params
    params.require(:movie).permit(:title, :description, category_ids:[])
  end

  def set_active_main_menu_item
    @main_menu[:movies][:active] = true
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  # GET /movies or /movies.json
  def index
    @page = (params[:page] || 1).to_i
    @number_of_pages = (Movie.all.size / MOVIES_PER_PAGE.to_f).ceil
    
    if @page > @number_of_pages || @page < 1
      redirect_to movies_path, alert: "Wrong page number!" 
    else
      @movies = Movie.paginate(page: params[:page], per_page: MOVIES_PER_PAGE)
    end
  end

  def category
    @page = (params[:page] || 1).to_i
    @cat = params[:category].capitalize
    category_movies = Movie.joins(:category).where("categories.title = ?", @cat)
    @number_of_pages = (category_movies.size / MOVIES_PER_PAGE.to_f).ceil

    if @page > @number_of_pages || @page < 1
      redirect_to movies_path, alert: "Wrong page number!"
    else
      @movies = category_movies.paginate(page: params[:page], per_page: MOVIES_PER_PAGE)
      render "index"
    end
  end

  # GET /movies/1 or /movies/1.json
  def show
    @movie = Movie.find(params[:id])
    @current_users_rating ||= @movie.ratings.where(user: current_user).pick(:rating)
    
    if @movie.ratings.any?
      @average_rating = @movie.ratings.average(:rating).round(2) 
      @ratings_count = @movie.ratings.count(:rating)
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :description, :rating, category_ids:[])
    end
end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/admin/movies/_form.html.erb
<%= form_with(model: [ :admin, movie ]) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group my-2">
    <%= form.label :title %>
    <%= form.text_field :title, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group my-2">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 10, class: "form-control" %>
  </div>

  <div class="form-check my-2">
    <%= form.label :Genres %>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :title do |b| %>
      <div class="row">
        <%= b.label do %>
          <div class="col-xs-4">
            <%= b.check_box(class: "form-check-input") %>
          </div>

          <div class="col-xs-8">
            <%= b.label %>
          </div>       
        <% end %>
      </div>
    <% end %>
  </div>



  <div class="form-group">
    <%= form.submit class: "btn btn-success my-3" %>
  </div>
<% end %>

app/views/admin/movies/edit.html.erb
<h3>Editing Movie</h3>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', admin_movie_path(@movie), class: "btn btn-secondary" %>
<%= link_to 'Back', admin_movies_path, class: "btn btn-secondary" %>

app/views/admin/movies/index.html.erb
<div class="d-flex">
  <h3 class="me-auto">Movies</h3>
  <div class="ml-auto p-2"><%= link_to "New Movie", :new_admin_movie, class: "btn btn-success btn-sm" %></div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Average rating</th>
      <th>Description</th>
      <th>Genres</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.title, admin_movie_path(movie) %></td>
        <td><%= movie.ratings.average(:rating).round(2) if movie.ratings.any? %></td>
        <td><%= movie.description %></td>
        <td>
          <% movie.category.each do |c| %>
            <%= link_to c.title, category_path(category: c.title.downcase) %><br>
          <% end %>
        </td>
          <td><%= link_to(image_tag("/pencil.svg", width: "20", class: "m-0"), edit_admin_movie_path(movie)) %></td>
          <td><%= link_to(image_tag("/trash.svg", width: "20", class: "m-0"), admin_movie_path(movie), method: :delete, data: { confirm: 'Are you sure?' }, class: "link-danger") %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>

app/views/admin/movies/new.html.erb
<h3>New Movie</h3>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', admin_movies_path, class: "btn btn-secondary" %>

app/views/admin/movies/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Genres:</strong>
  <% @movie.category.each do |c| %>
    <%= c.title %>
  <% end %>
</p>

<% if @movie.ratings.any? %>
  <p>
    <strong>Average rating:</strong>
    <%= @movie.ratings.average(:rating).round(2) %> (number of ratings: <%= @movie.ratings.count(:rating) %>)
  </p>
<% end %>

<br><br>

<%= link_to 'Back', admin_movies_path %>