config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'movies#index'
    get 'main', to: 'main#index', as: :main
    resources :categories, except: [:show]
    resources :movies
    get 'users', to: 'users#index', as: :users
  end

  match 'movies/:id/rate/:rating', to: 'ratings#index', via: [:get, :post], as: :rating
  get 'category/:category', to: 'movies#category', as: :category
  root to: "movies#index"

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', registration: 'register' }

  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorisation
  has_many :movies, through: :categorisation
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: %i[ edit update destroy ]

  def index
    @categories = Category.order(title: :asc)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to :admin_categories, notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: [:admin, @category] }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to :admin_categories, notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: [:admin, @category]  }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to :admin_categories, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:title)
  end

  def set_active_main_menu_item
    @main_menu[:categories][:active] = true
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_with(model: [ :admin, category ]) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-success my-3" %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h3>Editing Category</h3>

<%= render 'form', category: @category %>

<%= link_to 'Back', :admin_categories, class: "btn btn-secondary" %>

app/views/admin/categories/index.html.erb
<div class="d-flex">
  <h3 class="me-auto">Categories</h3>
  <div class="ml-auto p-2"><%= link_to "New Category", :new_admin_category, class: "btn btn-success btn-sm" %></div>
</div>

<table class="table table-sm w-50">
  <thead>
    <th>Title</th>
    <th>Number of movies</th>
    <th colspan="2">Actions</th>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.movies.count if category.movies.any? %></td>
        <td><%= link_to(image_tag("/pencil.svg", width: "20", class: "m-0"), edit_admin_category_path(category)) %></td>
        <td><%= link_to(image_tag("/trash.svg", width: "20", class: "m-0"), admin_category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: "link-danger") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/categories/new.html.erb
<h3>New Category</h3>

<%= render 'form', category: @category %>

<%= link_to 'Back', :admin_categories, class: "btn btn-secondary" %>